"""Gauge-invariant uniform-magnetic-field self-energy response for supercell GW.

This module implements the second ingredient entering Nourafkan, Kotliar, and
Tremblay, Phys. Rev. B 90, 125132 (2014), Eq. (2):

    Sigma_b = d Sigma_tilde^(B) / db |_{b=0},

with the dimensionless magnetic variable

    b = (e a^2 / hbar) B_z.

The derivation follows their Appendix A, Eq. (A13).  After the Peierls phase is
factored from G and Sigma, the gauge-invariant Green function obeys to first
order in a uniform B field

    G_b = Y_b + G Sigma_b G,

where the geometric magnetic source is

    Y_b = -(i/2) [ G J_x G J_y G - G J_y G J_x G ],

and

    J_alpha = -D_alpha G^{-1}.

For self-consistent GW the field derivative of the self-energy is obtained by
linearizing the same zero-field GW functional:

    Sigma_b = C_GW[G_b],

where C_GW[X] contains the Hartree, static-Fock, MT and AL pieces generated by
an arbitrary Green-function tangent X.  Consequently

    (I-L_GW) Sigma_b = C_GW[Y_b],

with

    L_GW[S] = C_GW[G S G].

This is solved with the same matrix-free restarted GMRES infrastructure as the
q=0 covariant-GW vertex equation.  No finite magnetic supercell and no finite-B
subtraction are required.

The interaction is density-density and has no explicit linear magnetic-field
coupling.  Thus all linear field dependence of the gauge-invariant GW
self-energy comes through G_b, consistent with the diagrammatic statement in
footnote 28 of Nourafkan et al.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .bulk_orbital_magnetization import (
    spectral_cartesian_covariant_derivatives,
    supercell_h0_cartesian_derivatives,
)
from .checkpoint import load_supercell_checkpoint, read_checkpoint_metadata
from .gw import _check_backend
from .orbital_moment import grid_and_params_from_checkpoint_metadata
from .supercell import (
    NSUP,
    build_supercell_h0,
    build_supercell_interaction,
)
from .supercell_cgw import (
    SupercellVertexOptions,
    _dynamic_corrections_direct,
    _dynamic_corrections_fft,
    _fock_from_x,
    _gmres_matrix_free,
    _hartree_from_x,
    _maxabs,
    _x_field,
)
from .supercell_gw import (
    compute_polarization_matrix,
    compute_screened_interaction_matrix,
    dyson_from_sigma_matrix,
)


@dataclass
class MagneticSelfEnergyResponse:
    """Uniform-B gauge-invariant GW self-energy response in code units."""

    Sigma_B_code: np.ndarray
    G_B_code: np.ndarray
    geometric_G_source_code: np.ndarray
    Sigma_H_B_code: np.ndarray
    Sigma_F_B_code: np.ndarray
    Sigma_MT_B_code: np.ndarray
    Sigma_AL1_B_code: np.ndarray
    Sigma_AL2_B_code: np.ndarray
    converged: bool
    iterations: int
    final_error: float
    source_sigma_max: float
    sigma_B_max: float
    geometric_G_source_max: float
    G_B_max: float
    momentum_backend: str


def geometric_uniform_B_green_source(
    G: np.ndarray,
    Jx: np.ndarray,
    Jy: np.ndarray,
) -> np.ndarray:
    """Return the explicit geometric term ``d G_tilde / db`` at fixed Sigma.

    Parameters
    ----------
    G
        Full zero-field Green function, shape ``(nf,nk1,nk2,norb,norb)``.
    Jx, Jy
        Dressed current vertices ``-D_x G^{-1}`` and ``-D_y G^{-1}``.  They may
        have the same shape as G or any shape broadcastable to G.

    Notes
    -----
    Nourafkan Appendix A13 gives, for physical B_z,

        G_B^geom = (i e / 2 hbar) G [d_x G^{-1} d_y G
                                    -d_y G^{-1} d_x G].

    With ``b=(e a^2/hbar)B_z``, derivatives measured in the repository length
    unit, ``J=-D G^{-1}``, and ``D G = G J G``, this becomes the expression
    implemented below.
    """
    G = np.asarray(G, dtype=complex)
    Jx = np.asarray(Jx, dtype=complex)
    Jy = np.asarray(Jy, dtype=complex)

    def chain(A, B):
        out = np.matmul(G, A)
        out = np.matmul(out, G)
        out = np.matmul(out, B)
        out = np.matmul(out, G)
        return out

    return -0.5j * (chain(Jx, Jy) - chain(Jy, Jx))


def self_energy_tangent_from_G_tangent(
    G: np.ndarray,
    W: np.ndarray,
    Vq: np.ndarray,
    X: np.ndarray,
    grid,
    opts: SupercellVertexOptions,
) -> tuple[np.ndarray, tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
    """Apply the split-GW functional derivative ``delta Sigma / delta G`` to X.

    This is the same Hartree/Fock/MT/AL functional derivative used by cGW, but
    the input is an arbitrary Green-function tangent X rather than necessarily
    ``G Gamma G``.
    """
    backend = _check_backend(opts.momentum_backend)
    X = np.asarray(X, dtype=complex)
    if X.shape != G.shape:
        raise ValueError(f"X shape {X.shape} != G shape {G.shape}")

    zero = np.zeros_like(X)
    gh = _hartree_from_x(X, Vq[0, 0], grid) if opts.include_hartree else zero.copy()
    gf = _fock_from_x(X, Vq, grid, backend) if opts.include_fock else zero.copy()
    Wc = W - Vq[None, :, :, :, :]
    dyn = _dynamic_corrections_fft if backend == "fft" else _dynamic_corrections_direct
    gmt, gal1, gal2 = dyn(
        G,
        W,
        Wc,
        X,
        grid,
        include_mt=opts.include_mt,
        include_al=opts.include_al,
    )
    parts = (gh, gf, gmt, gal1, gal2)
    return gh + gf + gmt + gal1 + gal2, parts


def solve_uniform_B_self_energy_derivative(
    G: np.ndarray,
    W: np.ndarray,
    Vq: np.ndarray,
    Jx: np.ndarray,
    Jy: np.ndarray,
    grid,
    *,
    opts: SupercellVertexOptions = SupercellVertexOptions(),
    initial_sigma_B: np.ndarray | None = None,
) -> MagneticSelfEnergyResponse:
    """Solve ``d Sigma_tilde^(B)/db`` for self-consistent split GW.

    The unknown ``S=Sigma_B`` satisfies

        S = C[Y + G S G],

    where C is the GW self-energy tangent and Y is the geometric magnetic
    source from Nourafkan Eq. (A13).  The equation is linear in S.
    """
    G = np.asarray(G, dtype=complex)
    W = np.asarray(W, dtype=complex)
    Vq = np.asarray(Vq, dtype=complex)
    backend = _check_backend(opts.momentum_backend)

    Y = geometric_uniform_B_green_source(G, Jx, Jy)
    source_sigma, _ = self_energy_tangent_from_G_tangent(G, W, Vq, Y, grid, opts)

    if initial_sigma_B is None:
        x0 = np.array(source_sigma, copy=True)
    else:
        arr = np.asarray(initial_sigma_B, dtype=complex)
        if arr.shape != G.shape:
            raise ValueError(f"initial_sigma_B shape {arr.shape} != G shape {G.shape}")
        x0 = np.array(arr, copy=True)

    def apply_A(S):
        induced_X = _x_field(G, np.asarray(S, dtype=complex))
        induced_sigma, _ = self_energy_tangent_from_G_tangent(
            G, W, Vq, induced_X, grid, opts
        )
        return np.asarray(S, dtype=complex) - induced_sigma

    if _maxabs(source_sigma) == 0.0:
        Sigma_B = np.zeros_like(G)
        converged = True
        iterations = 0
        error = 0.0
    elif str(opts.solver).strip().lower() == "gmres":
        Sigma_B, converged, iterations, error = _gmres_matrix_free(
            apply_A,
            source_sigma,
            x0,
            tol=float(opts.tol),
            max_iter=int(opts.max_iter),
            restart=int(opts.gmres_restart),
            verbose=bool(opts.verbose),
        )
    else:
        Sigma_B = np.array(x0, copy=True)
        converged = False
        error = float("inf")
        iterations = 0
        for iterations in range(1, int(opts.max_iter) + 1):
            residual = source_sigma - apply_A(Sigma_B)
            error = _maxabs(residual)
            if opts.verbose:
                print(
                    f"uniform-B Sigma linear iter {iterations:4d}: "
                    f"residual_max={error:.3e}, backend={backend}"
                )
            if error < float(opts.tol):
                converged = True
                break
            Sigma_B += float(opts.mixing) * residual

    induced_X = _x_field(G, Sigma_B)
    G_B = Y + induced_X
    sigma_total, parts = self_energy_tangent_from_G_tangent(G, W, Vq, G_B, grid, opts)
    gh, gf, gmt, gal1, gal2 = parts
    error = _maxabs(sigma_total - Sigma_B)
    converged = bool(np.isfinite(error) and error < float(opts.tol))

    return MagneticSelfEnergyResponse(
        Sigma_B_code=np.asarray(Sigma_B, dtype=complex),
        G_B_code=np.asarray(G_B, dtype=complex),
        geometric_G_source_code=np.asarray(Y, dtype=complex),
        Sigma_H_B_code=np.asarray(gh, dtype=complex),
        Sigma_F_B_code=np.asarray(gf, dtype=complex),
        Sigma_MT_B_code=np.asarray(gmt, dtype=complex),
        Sigma_AL1_B_code=np.asarray(gal1, dtype=complex),
        Sigma_AL2_B_code=np.asarray(gal2, dtype=complex),
        converged=converged,
        iterations=int(iterations),
        final_error=float(error),
        source_sigma_max=_maxabs(source_sigma),
        sigma_B_max=_maxabs(Sigma_B),
        geometric_G_source_max=_maxabs(Y),
        G_B_max=_maxabs(G_B),
        momentum_backend=backend,
    )


def solve_checkpoint_uniform_B_self_energy_derivative(
    path: str | Path,
    *,
    require_converged: bool = True,
    opts: SupercellVertexOptions = SupercellVertexOptions(),
) -> MagneticSelfEnergyResponse:
    """Load a zero-source 18-site checkpoint and solve its uniform-B Sigma_B."""
    path = Path(path)
    meta = read_checkpoint_metadata(path)
    if require_converged and not bool(meta.get("converged", False)):
        raise ValueError(
            f"Checkpoint {path} is marked nonconverged "
            f"(final_error={meta.get('final_error')!r})."
        )
    if abs(float(meta.get("source", 0.0))) > 1e-14:
        raise ValueError("uniform-B response currently requires a zero-source checkpoint")

    grid, params = grid_and_params_from_checkpoint_metadata(meta)
    seed, _, _ = load_supercell_checkpoint(
        path, params, grid, float(meta["primitive_filling"])
    )
    h0 = build_supercell_h0(grid.kmesh(), params, source_strength=0.0)
    sigma_total = (
        np.asarray(seed.Sigma_GW, dtype=complex)
        + np.asarray(seed.Sigma_H, dtype=complex)[None, None, None, :, :]
    )
    G = dyson_from_sigma_matrix(
        h0,
        grid,
        float(seed.mu),
        np.asarray(seed.Sigma_H, dtype=complex),
        np.asarray(seed.Sigma_GW, dtype=complex),
    )

    Dx_H0, Dy_H0 = supercell_h0_cartesian_derivatives(grid.kmesh(), params)
    Dx_Sigma, Dy_Sigma = spectral_cartesian_covariant_derivatives(sigma_total)
    Jx = Dx_H0[None, :, :, :, :] + Dx_Sigma
    Jy = Dy_H0[None, :, :, :, :] + Dy_Sigma

    Vq = build_supercell_interaction(grid.qmesh(), params)
    P = compute_polarization_matrix(G, grid, backend=opts.momentum_backend)
    W = compute_screened_interaction_matrix(P, Vq)

    return solve_uniform_B_self_energy_derivative(
        G,
        W,
        Vq,
        Jx,
        Jy,
        grid,
        opts=opts,
    )
