"""Tail-consistent static cGW response with the covariant SOX kernel.

For a self-consistent GW+SOX background the response equation is

    Gamma = K
          + D Sigma_H[X]
          + D Sigma_F[X]
          + D Sigma_c[X]
          + D Sigma_SOX[X],

with X=G Gamma G.  ``D Sigma_c`` is the existing MT+AL part generated by the
retarded GW interaction W-V.  ``D Sigma_SOX`` is the sum of the three crossed
second-order-exchange terms implemented in :mod:`rubycgw.sox_covariant`.

This module is also useful on a *fixed ordinary GW background*.  That mode is a
diagnostic only: it isolates the explicit SOX kernel while keeping G fixed.  A
quantity labelled ``cGW+SOX`` in production scans should use a self-consistent
GW+SOX background unless the output explicitly says ``fixed_GW``.
"""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from .ed_cgw_benchmark import static_response_from_gammas
from .grids import MatsubaraGrid
from .gw import _check_backend
from .response_tail import (
    TailReference,
    build_tail_hf_context,
    build_tail_reference,
    reference_tail_remainder,
)
from .sox_covariant import (
    SOXOptions,
    compute_sox_vertex_periodic,
    estimate_static_vertex,
)
from .supercell_cgw import (
    SupercellVertexOptions,
    _check_vertex_solver,
    _dynamic_corrections_direct,
    _dynamic_corrections_fft,
    _gmres_matrix_free,
    _initial_gamma_field,
    _maxabs,
    _x_field,
)


@dataclass
class GWSOXVertexResult:
    Gamma: np.ndarray
    Gamma_H: np.ndarray
    Gamma_F: np.ndarray
    Gamma_MT: np.ndarray
    Gamma_AL1: np.ndarray
    Gamma_AL2: np.ndarray
    Gamma_SOX: np.ndarray
    converged: bool
    iterations: int
    final_error: float
    solver: str = "gmres"


def _dynamic_parts(G, W, Vq, X, grid, opts):
    backend = _check_backend(opts.momentum_backend)
    Wc = np.asarray(W, dtype=complex) - np.asarray(Vq, dtype=complex)[None, ...]
    dyn = _dynamic_corrections_fft if backend == "fft" else _dynamic_corrections_direct
    return dyn(
        G,
        W,
        Wc,
        X,
        grid,
        include_mt=opts.include_mt,
        include_al=opts.include_al,
    )


def solve_vertex_q0_tail_sox(
    G: np.ndarray,
    W: np.ndarray,
    Vq: np.ndarray,
    K: np.ndarray,
    grid: MatsubaraGrid,
    reference: TailReference,
    h_sox_ref: np.ndarray,
    mu: float,
    vertex_opts: SupercellVertexOptions = SupercellVertexOptions(),
    sox_opts: SOXOptions = SOXOptions(),
    initial_gamma: np.ndarray | None = None,
) -> GWSOXVertexResult:
    """Solve the production q=0 covariant GW+SOX vertex equation.

    ``reference`` is the same H/F-tail reference differentiated by production
    cGW.  ``h_sox_ref`` is a static k-resolved reference used only to complete
    the Matsubara tails of the SOX tau reconstruction; for a converged GW+SOX
    background it should normally be ``h0 + Sigma_H + Sigma_F``.
    """
    G = np.asarray(G, dtype=complex)
    W = np.asarray(W, dtype=complex)
    Vq = np.asarray(Vq, dtype=complex)
    K = np.asarray(K, dtype=complex)
    h_sox_ref = np.asarray(h_sox_ref, dtype=complex)
    norb = int(G.shape[-1])
    if K.shape != (norb, norb):
        raise ValueError(f"K shape {K.shape} != {(norb, norb)}")
    if Vq.shape != (grid.nk1, grid.nk2, norb, norb):
        raise ValueError("unexpected Vq shape")
    if W.shape != (grid.nb, grid.nk1, grid.nk2, norb, norb):
        raise ValueError("unexpected W shape")
    if h_sox_ref.shape != (grid.nk1, grid.nk2, norb, norb):
        raise ValueError("unexpected h_sox_ref shape")
    sox_opts.validate()

    solver = _check_vertex_solver(vertex_opts.solver)
    backend = _check_backend(vertex_opts.momentum_backend)
    Kfield = np.broadcast_to(K, G.shape).copy()
    ctx = build_tail_hf_context(
        reference,
        K,
        Vq,
        grid,
        q_index=(0, 0),
        m_ext=0,
        backend=backend,
        include_hartree=vertex_opts.include_hartree,
        include_fock=vertex_opts.include_fock,
    )
    hconst, fconst = ctx.constant_vertex_parts(G)
    rhs = Kfield + hconst + fconst
    Gamma0 = _initial_gamma_field(initial_gamma, rhs)

    def linear_parts(field):
        field = np.asarray(field, dtype=complex)
        X = _x_field(G, field)
        gh, gf = ctx.linear_vertex_parts(X, G)
        gmt, gal1, gal2 = _dynamic_parts(
            G, W, Vq, X, grid, vertex_opts
        )
        gsox = compute_sox_vertex_periodic(
            G,
            field,
            Vq,
            h_sox_ref,
            float(mu),
            grid,
            opts=sox_opts,
        )
        return gh, gf, gmt, gal1, gal2, gsox

    def linear_kernel(field):
        parts = linear_parts(field)
        return sum(parts[1:], parts[0])

    if solver == "gmres":
        def apply_A(field):
            field = np.asarray(field, dtype=complex)
            return field - linear_kernel(field)

        Gamma, converged, it, err = _gmres_matrix_free(
            apply_A,
            rhs,
            Gamma0,
            tol=float(vertex_opts.tol),
            max_iter=int(vertex_opts.max_iter),
            restart=int(vertex_opts.gmres_restart),
            verbose=bool(vertex_opts.verbose),
        )
    else:
        Gamma = np.array(Gamma0, copy=True)
        converged = False
        err = float("inf")
        it = 0
        for it in range(1, int(vertex_opts.max_iter) + 1):
            residual = rhs + linear_kernel(Gamma) - Gamma
            err = _maxabs(residual)
            if vertex_opts.verbose:
                print(
                    f"tail-consistent cGW+SOX iter {it:4d}: "
                    f"residual_max={err:.3e}"
                )
            if err < float(vertex_opts.tol):
                converged = True
                break
            Gamma += float(vertex_opts.mixing) * residual

    X = _x_field(G, Gamma)
    gh, gf = ctx.total_vertex_parts(X, G)
    gmt, gal1, gal2 = _dynamic_parts(G, W, Vq, X, grid, vertex_opts)
    gsox = compute_sox_vertex_periodic(
        G,
        Gamma,
        Vq,
        h_sox_ref,
        float(mu),
        grid,
        opts=sox_opts,
    )
    total = gh + gf + gmt + gal1 + gal2 + gsox
    err = _maxabs(Kfield + total - Gamma)
    converged = bool(np.isfinite(err) and err < float(vertex_opts.tol))

    return GWSOXVertexResult(
        Gamma=Gamma,
        Gamma_H=gh,
        Gamma_F=gf,
        Gamma_MT=gmt,
        Gamma_AL1=gal1,
        Gamma_AL2=gal2,
        Gamma_SOX=gsox,
        converged=converged,
        iterations=int(it),
        final_error=float(err),
        solver=solver,
    )


def _observable_tail_reference(
    h_static_ref: np.ndarray,
    mu: float,
    grid: MatsubaraGrid,
) -> TailReference:
    h = np.asarray(h_static_ref, dtype=complex)
    norb = int(h.shape[-1])
    return build_tail_reference(
        h,
        float(mu),
        np.zeros((norb, norb), dtype=complex),
        grid,
    )


def static_response_tail_completed(
    G: np.ndarray,
    left_vertices: np.ndarray,
    right_gammas: list[np.ndarray] | np.ndarray,
    grid: MatsubaraGrid,
    h_static_ref: np.ndarray,
    mu: float,
    *,
    edge_points: int = 2,
) -> dict[str, np.ndarray]:
    """Return represented-box and analytic-tail-completed static responses.

    The raw value is exactly the historical finite-box contraction

        -T/Nk sum Tr[K G Gamma G].

    The completed value adds the missing static-reference tail.  Both are kept
    because ED static susceptibilities contain the full Matsubara sum, while
    the historical cGW output reported only the represented box.
    """
    G = np.asarray(G, dtype=complex)
    K = np.asarray(left_vertices, dtype=complex)
    gammas = [np.asarray(x, dtype=complex) for x in right_gammas]
    raw = static_response_from_gammas(G, K, gammas, grid)
    ref = _observable_tail_reference(h_static_ref, mu, grid)
    correction = np.zeros_like(raw)
    for b, gamma in enumerate(gammas):
        S = estimate_static_vertex(gamma, edge_points=edge_points)
        C = reference_tail_remainder(
            ref, S, grid, q_index=(0, 0), m_ext=0
        )
        correction[:, b] = -(1.0 / float(grid.nk)) * np.einsum(
            "aij,xyji->a", K, C, optimize=True
        )
    return {
        "raw": raw,
        "tail_correction": correction,
        "completed": raw + correction,
    }


def static_gg_tail_completed(
    G: np.ndarray,
    vertices: np.ndarray,
    grid: MatsubaraGrid,
    h_static_ref: np.ndarray,
    mu: float,
    *,
    edge_points: int = 2,
) -> dict[str, np.ndarray]:
    """GG static bubble in the same raw/completed convention as cGW."""
    K = np.asarray(vertices, dtype=complex)
    gammas = [np.broadcast_to(k, np.asarray(G).shape).copy() for k in K]
    return static_response_tail_completed(
        G,
        K,
        gammas,
        grid,
        h_static_ref,
        mu,
        edge_points=edge_points,
    )


__all__ = [
    "GWSOXVertexResult",
    "solve_vertex_q0_tail_sox",
    "static_response_tail_completed",
    "static_gg_tail_completed",
]
